module.exports = {
    name : "Bridle",
    endpointUrl : "opc.tcp://10.214.16.240:4840",
    tags : [
		"ns=3;s=\"Kamera_sinyalleri\".\"Kapi\"",
		"ns=3;s=\"Alarms_DB\".\"Roller_1_Vibrasyon\".\"Alarm\"",
		"ns=3;s=\"Alarms_DB\".\"Roller_1_Vibrasyon\".\"Uyarı\"",
		"ns=3;s=\"Alarms_DB\".\"Roller_2_Vibrasyon\".\"Alarm\"",
		"ns=3;s=\"Alarms_DB\".\"Roller_2_Vibrasyon\".\"Uyarı\"",
		"ns=3;s=\"Kamera_sinyalleri\".\"Kamera_plc_comm\"",
		"ns=3;s=\"Kamera_sinyalleri\".\"Kapi\"",
		"ns=3;s=\"Pruf_technic\".\"islenmis_sensor_verileri\"",
		"ns=3;s=\"Pruf_technic\".\"islenmis_sensor_verileri_real\"",
		"ns=3;s=\"Pruf_technic\".\"sensor_durum_bilgisi\"",
		"ns=3;s=\"Pruf_technic\".\"Vipguarda_Gonderilen_Degerler\"",
		"ns=3;s=\"Pruf_technic\".\"pruf_ham_okunan_veriler\".\"ilk_grup_veriler\"",
		"ns=3;s=\"Pruf_technic\".\"pruf_ham_okunan_veriler\".\"ikinci_grup_veriler\"",
		
		//GEARBOX 1
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Acceleration Spectrum / GMF1\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Acceleration Spectrum / GMF2\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A2 - 2H / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Acceleration Spectrum / GMF1\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Acceleration Spectrum / GMF2\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A3 - 3H / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Acceleration Spectrum / GMF1\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Acceleration Spectrum / GMF2\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Gearbox\".\"A4 - 3A / Velocity Spectrum / 2X\"",
		
		//MOTOR 1
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Motor\".\"A1 - 1V / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Motor\".\"A1 - 1V / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Motor\".\"A1 - 1V / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Motor\".\"A1 - 1V / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Motor\".\"A1 - 1V / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Motor\".\"A1 - 1V / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Motor\".\"A1 - 1V / Velocity Spectrum / 2xLF\"",
		
		//ROLLER 1
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A5 - 4H / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A5 - 4H / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A5 - 4H / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A5 - 4H / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A5 - 4H / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A5 - 4H / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A6 - 5V / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A6 - 5V / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A6 - 5V / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A6 - 5V / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A6 - 5V / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"A6 - 5V / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_1\".\"Roller\".\"Speed / Machine Speed\"",
		
		//GEARBOX 2
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Acceleration Spectrum / GMF1\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Acceleration Spectrum / GMF2\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A8 - 2H / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Acceleration Spectrum / GMF1\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Acceleration Spectrum / GMF2\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A9 - 3H / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Acceleration Spectrum / GMF1\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Acceleration Spectrum / GMF2\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Gearbox\".\"A10 - 3A / Velocity Spectrum / 2X\"",

		//Motor 2
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Motor\".\"A7 - 1V / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Motor\".\"A7 - 1V / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Motor\".\"A7 - 1V / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Motor\".\"A7 - 1V / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Motor\".\"A7 - 1V / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Motor\".\"A7 - 1V / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Motor\".\"A7 - 1V / Velocity Spectrum / 2xLF\"",
		
		//ROLLER 2
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A11 - 4H / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A11 - 4H / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A11 - 4H / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A11 - 4H / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A11 - 4H / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A11 - 4H / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A12 - 5V / Acceleration Overall / 0-P\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A12 - 5V / Acceleration Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A12 - 5V / Envelope Spectrum / Envelope_Pk\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A12 - 5V / Velocity Overall / RMS\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A12 - 5V / Velocity Spectrum / 1X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"A12 - 5V / Velocity Spectrum / 2X\"",
		"ns=3;s=\"Pruf_technic\".\"Bridle_Roll_2\".\"Roller\".\"Speed / Machine Speed VIBGUARD\"",
		
		"ns=3;s=\"SYSTEM\".\"Mod\".\"Manuel\"",
		"ns=3;s=\"SYSTEM\".\"Mod\".\"Otomatik\"",
		"ns=3;s=\"SYSTEM\".\"Otomatik\".\"Başlat\"",
		"ns=3;s=\"SYSTEM\".\"Otomatik\".\"Durdur\"",
		"ns=3;s=\"SYSTEM\".\"Otomatik\".\"Hız\"",
		"ns=3;s=\"SYSTEM\".\"Manuel_Roller_A\".\"Geri\"",
		"ns=3;s=\"SYSTEM\".\"Manuel_Roller_A\".\"Hız\"",
		"ns=3;s=\"SYSTEM\".\"Manuel_Roller_A\".\"İleri\"",
		"ns=3;s=\"SYSTEM\".\"Manuel_Roller_B\".\"Geri\"",
		"ns=3;s=\"SYSTEM\".\"Manuel_Roller_B\".\"Hız\"",
		"ns=3;s=\"SYSTEM\".\"Manuel_Roller_B\".\"İleri\"",
		
		//ALARMLAR GEARBOX 1
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Gearbox\".\"A2 - 2H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Gearbox\".\"A3 - 3H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Gearbox\".\"A4 - 3A / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Motor\".\"A1 - 1V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Roller\".\"A5 - 4H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Roller\".\"A6 - 5V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Roller\".\"PT1.1\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_A\".\"Roller\".\"PT1.2\"",

		//UYARILAR GEARBOX 1
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Gearbox\".\"A2 - 2H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Gearbox\".\"A3 - 3H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Gearbox\".\"A4 - 3A / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Motor\".\"A1 - 1V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Roller\".\"A5 - 4H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Roller\".\"A6 - 5V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Roller\".\"PT1.1\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_A\".\"Roller\".\"PT1.2\"",

		//LIMITLER GEARBOX 2
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Gearbox\".\"A8 - 2H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Gearbox\".\"A9 - 3H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Gearbox\".\"A10 - 3A / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Motor\".\"A7 - 1V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Roller\".\"A11 - 4H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Roller\".\"A12 - 5V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Roller\".\"PT2.1\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Alarm\".\"Limit_Roller_B\".\"Roller\".\"PT2.2\"",
		
		//UYARILAR GEARBOX 2
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Gearbox\".\"A8 - 2H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Gearbox\".\"A9 - 3H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Gearbox\".\"A10 - 3A / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Motor\".\"A7 - 1V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Roller\".\"A11 - 4H / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Roller\".\"A12 - 5V / Velocity Overall / RMS\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Roller\".\"PT2.1\"",
		"ns=3;s=\"SYSTEM\".\"Limitler\".\"Uyarı\".\"Limit_Roller_B\".\"Roller\".\"PT2.2\""

    ]
};
