module.exports = {
    name : "Kitting",
    endpointUrl : "opc.tcp://10.214.16.160:4840",
    tags : [
        "ns=3;s=\"OPC\".\"JigRecipe\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer0\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer1\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer10\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer11\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer12\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer13\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer14\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer15\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer16\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer17\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer2\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer3\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer4\"",
		"ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer5\"",
        "ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer6\"",        
		"ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer7\"",        
		"ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer8\"",        
		"ns=3;s=\"OPC\".\"PickKittingSubAssyBuffer9\"", 
		
		"ns=3;s=\"OPC\".\"PickKTPB0000\"",        
		"ns=3;s=\"OPC\".\"PickKTPB0001\"",        
		"ns=3;s=\"OPC\".\"PickKTPB0002\"",        
		"ns=3;s=\"OPC\".\"PickKTPB0003\"",        
		"ns=3;s=\"OPC\".\"PickKTPB0004\"",        
		"ns=3;s=\"OPC\".\"PickKTPB0005\"",        
		"ns=3;s=\"OPC\".\"PutKTPB0010\"",
		"ns=3;s=\"OPC\".\"PutKTPB0011\"",
		
		"ns=3;s=\"OPC\".\"St410BadPartCounter\"",        
		"ns=3;s=\"OPC\".\"St410BearingCapBoxRefreshed\"",        
		"ns=3;s=\"OPC\".\"St410BearingCapBoxReplenishAGVReady\"",        
		"ns=3;s=\"OPC\".\"St410BearingCapBoxReplenishAGVRequest\"",        
		"ns=3;s=\"OPC\".\"St410BearingCapBoxRequest\"",        
		"ns=3;s=\"OPC\".\"St410ClosedCoverBoxRefreshed\"",        
		"ns=3;s=\"OPC\".\"St410ClosedCoverBoxReplenishAGVReady\"",
		"ns=3;s=\"OPC\".\"St410ClosedCoverBoxReplenishAGVRequest\"",
		
		"ns=3;s=\"OPC\".\"St410ClosedCoverBoxRequest\"",        
		"ns=3;s=\"OPC\".\"St410CustomSetOnTrolley\"",        
		"ns=3;s=\"OPC\".\"St410CycleTime\"",        
		"ns=3;s=\"OPC\".\"St410EnergyConsumption\"",        
		"ns=3;s=\"OPC\".\"St410ErrorFlag\"",        
		"ns=3;s=\"OPC\".\"St410Feeder30304NOK\"",        
		"ns=3;s=\"OPC\".\"St410Feeder32205NOK\"",
		"ns=3;s=\"OPC\".\"St410FlippingPartInCycle\"",
		
		
		"ns=3;s=\"OPC\".\"St410Gear_Ratio\"",        
		"ns=3;s=\"OPC\".\"St410GoodPartCounter\"",        
		"ns=3;s=\"OPC\".\"St410InputOpenCoverBoxRefreshed\"",        
		"ns=3;s=\"OPC\".\"St410InputOpenCoverBoxReplenishAGVReady\"",        
		"ns=3;s=\"OPC\".\"St410InputOpenCoverBoxReplenishAGVRequest\"",        
		"ns=3;s=\"OPC\".\"St410InputOpenCoverBoxRequest\"",        
		"ns=3;s=\"OPC\".\"St410JigPresent\"",
		"ns=3;s=\"OPC\".\"St410KittingJigID\"",
		
		"ns=3;s=\"OPC\".\"St410LifeBit\"",        
		"ns=3;s=\"OPC\".\"St410MachineState\"",        
		"ns=3;s=\"OPC\".\"St410NOKReason\"",        
		"ns=3;s=\"OPC\".\"St410OperatorID\"",        
		"ns=3;s=\"OPC\".\"St410OperatorLoggedInOut\"",        
		"ns=3;s=\"OPC\".\"St410OutputOpenCoverBoxRefreshed\"",        
		"ns=3;s=\"OPC\".\"St410OutputOpenCoverBoxReplenishAGVReady\"",
		"ns=3;s=\"OPC\".\"St410OutputOpenCoverBoxReplenishAGVRequest\"",
		
		"ns=3;s=\"OPC\".\"St410OutputOpenCoverBoxRequest\"",        
		"ns=3;s=\"OPC\".\"St410PartResult\"",        
		"ns=3;s=\"OPC\".\"St410ProcessStatus\"",        
		"ns=3;s=\"OPC\".\"St410Product_Type\"",        
		"ns=3;s=\"OPC\".\"St410RobotAx1ActPosition\"",        
		"ns=3;s=\"OPC\".\"St410RobotAx2ActPosition\"",        
		"ns=3;s=\"OPC\".\"St410RobotAx3ActPosition\"",
		"ns=3;s=\"OPC\".\"St410RobotAx4ActPosition\"",
		
		"ns=3;s=\"OPC\".\"St410RobotAx5ActPosition\"",       
		"ns=3;s=\"OPC\".\"St410RobotAx6ActPosition\"",        
		//"ns=3;s=\"OPC\".\"St410RobotCycleTime\"",
		"ns=3;s=\"OPC\".\"St410RobotGripperStatus\"",
		
		"ns=3;s=\"OPC\".\"St410RobotInHomePosition\"",        
		"ns=3;s=\"OPC\".\"St410RobotSpeed\"",        
		"ns=3;s=\"OPC\".\"St410RobotStatus\"",
		"ns=3;s=\"OPC\".\"St410SafetyStatus\"",
		
		"ns=3;s=\"OPC\".\"St410ShiftChange\"",        
		"ns=3;s=\"OPC\".\"St410StopReason\"",        
		"ns=3;s=\"OPC\".\"St410TotalPartCounter\"",
		"ns=3;s=\"OPC\".\"St410TrolleyPickReady\"",
		
		"ns=3;s=\"OPC\".\"St410TrolleyPosStatus\"",        
		"ns=3;s=\"OPC\".\"St410TrolleyRefreshed\"",        
		"ns=3;s=\"OPC\".\"St410WorkOrder\"",
		"ns=3;s=\"OPC\".\"St410WorkOrderActive\""
    ] 
};