module.exports = {
    name : "ST120",
    endpointUrl : "opc.tcp://10.214.16.40:4840",
    tags : [
        "ns=3;s=\"OPC\".\"St120BadPartCounter\"",
        "ns=3;s=\"OPC\".\"St120BeforeStatePrintBarcode\"",
        "ns=3;s=\"OPC\".\"St120CycleTime\"",
        "ns=3;s=\"OPC\".\"St120EnergyConsumption\"",
        "ns=3;s=\"OPC\".\"St120ErrorFlag\"",
        "ns=3;s=\"OPC\".\"St120Gear_Ratio\"",
        "ns=3;s=\"OPC\".\"St120GoodPartCounter\"",
        "ns=3;s=\"OPC\".\"St120HandScannerError\"",
        "ns=3;s=\"OPC\".\"St120HandScannerPartCode\"",
        "ns=3;s=\"OPC\".\"St120HandScannerReady\"",
        "ns=3;s=\"OPC\".\"St120LifeBit\"",
        "ns=3;s=\"OPC\".\"St120MachineState\"",
        "ns=3;s=\"OPC\".\"St120OperatorID\"",
        "ns=3;s=\"OPC\".\"St120OperatorLoggedInOut\"",
        "ns=3;s=\"OPC\".\"St120PartPresent\"",
        "ns=3;s=\"OPC\".\"St120PrinterCommError\"",
        "ns=3;s=\"OPC\".\"St120PrinterCommStatus\"",
        "ns=3;s=\"OPC\".\"St120ProcessStatus\"",
        "ns=3;s=\"OPC\".\"St120Product_Type\"",
        "ns=3;s=\"OPC\".\"St120SafetyStatus\"",
        "ns=3;s=\"OPC\".\"St120ScrewerError\"",
        "ns=3;s=\"OPC\".\"St120ScrewerProgNo\"",
        "ns=3;s=\"OPC\".\"St120ScrewerReady\"",
        "ns=3;s=\"OPC\".\"St120ScrewingAngle\"",
        "ns=3;s=\"OPC\".\"St120SerialNumber\"",
        "ns=3;s=\"OPC\".\"St120ShiftChange\"",
        "ns=3;s=\"OPC\".\"St120StopReason\"",
        "ns=3;s=\"OPC\".\"St120StopReasonMES\"",
        "ns=3;s=\"OPC\".\"St120TotalPartCounter\"",
        "ns=3;s=\"OPC\".\"St120TransferReadyInterroll\"",

        "ns=3;s=\"OPC\".\"St120WorkOrder\"",
        "ns=3;s=\"OPC\".\"St120WP4_CycleTime\"",
        "ns=3;s=\"OPC\".\"St120WP4JigID\"",
        "ns=3;s=\"OPC\".\"St120Wp4NOKReasonMES\"",
        "ns=3;s=\"OPC\".\"St120WP4WorkOrderActive\"",
        "ns=3;s=\"OPC\".\"St120WP5_CycleTime\"",
        "ns=3;s=\"OPC\".\"St120WP5JigID\"",
        "ns=3;s=\"OPC\".\"St120Wp5NOKReasonMES\"",
        "ns=3;s=\"OPC\".\"St120WP5OperatorCycleTime\"",

        "ns=3;s=\"OPC\".\"St120WP5WorkOrderActive\"",
        "ns=3;s=\"OPC\".\"St120WP6_CycleTime\"",
        "ns=3;s=\"OPC\".\"St120WP6JigID\"",
        "ns=3;s=\"OPC\".\"St120Wp6NOKReasonMES\"",
        "ns=3;s=\"OPC\".\"St120WP6NOKStatus\"",
        "ns=3;s=\"OPC\".\"St120WP6WorkOrderActive\"",
        "ns=3;s=\"OPC\".\"St120WP7_CycleTime\"",
        "ns=3;s=\"OPC\".\"St120WP7JigID\"",
        "ns=3;s=\"OPC\".\"St120Wp7NOKReasonMES\"",
        "ns=3;s=\"OPC\".\"St120WP7NOKStatus\"",
        "ns=3;s=\"OPC\".\"St120WP7WorkOrderActive\""

    ] 
};